using System.Text.Json.Serialization;
using IntelligenceX.Chat.Abstractions.Policy;
using IntelligenceX.Chat.Abstractions.Protocol;

namespace IntelligenceX.Chat.Abstractions.Serialization;

/// <summary>
/// Source-generated System.Text.Json context for the chat service protocol.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(ChatServiceRequest))]
[JsonSerializable(typeof(ChatServiceMessage))]
[JsonSerializable(typeof(HelloRequest))]
[JsonSerializable(typeof(EnsureLoginRequest))]
[JsonSerializable(typeof(StartChatGptLoginRequest))]
[JsonSerializable(typeof(ChatGptLoginPromptResponseRequest))]
[JsonSerializable(typeof(CancelChatGptLoginRequest))]
[JsonSerializable(typeof(ListToolsRequest))]
[JsonSerializable(typeof(GetBackgroundSchedulerStatusRequest))]
[JsonSerializable(typeof(SetBackgroundSchedulerStateRequest))]
[JsonSerializable(typeof(SetBackgroundSchedulerMaintenanceWindowsRequest))]
[JsonSerializable(typeof(SetBackgroundSchedulerBlockedPacksRequest))]
[JsonSerializable(typeof(SetBackgroundSchedulerBlockedThreadsRequest))]
[JsonSerializable(typeof(CheckToolHealthRequest))]
[JsonSerializable(typeof(ListProfilesRequest))]
[JsonSerializable(typeof(SetProfileRequest))]
[JsonSerializable(typeof(ApplyRuntimeSettingsRequest))]
[JsonSerializable(typeof(ListModelsRequest))]
[JsonSerializable(typeof(ListModelFavoritesRequest))]
[JsonSerializable(typeof(SetModelFavoriteRequest))]
[JsonSerializable(typeof(InvokeToolRequest))]
[JsonSerializable(typeof(CancelChatRequest))]
[JsonSerializable(typeof(ChatRequest))]
[JsonSerializable(typeof(ChatRequestOptions))]
[JsonSerializable(typeof(ErrorMessage))]
[JsonSerializable(typeof(AckMessage))]
[JsonSerializable(typeof(HelloMessage))]
[JsonSerializable(typeof(LoginStatusMessage))]
[JsonSerializable(typeof(NativeUsageSnapshotDto))]
[JsonSerializable(typeof(NativeRateLimitStatusDto))]
[JsonSerializable(typeof(NativeRateLimitWindowDto))]
[JsonSerializable(typeof(NativeCreditsSnapshotDto))]
[JsonSerializable(typeof(ChatGptLoginStartedMessage))]
[JsonSerializable(typeof(ChatGptLoginUrlMessage))]
[JsonSerializable(typeof(ChatGptLoginPromptMessage))]
[JsonSerializable(typeof(ChatGptLoginCompletedMessage))]
[JsonSerializable(typeof(ToolListMessage))]
[JsonSerializable(typeof(BackgroundSchedulerStatusMessage))]
[JsonSerializable(typeof(ToolHealthMessage))]
[JsonSerializable(typeof(ProfileListMessage))]
[JsonSerializable(typeof(ModelListMessage))]
[JsonSerializable(typeof(ModelFavoritesMessage))]
[JsonSerializable(typeof(InvokeToolResultMessage))]
[JsonSerializable(typeof(ChatStatusMessage))]
[JsonSerializable(typeof(ChatDeltaMessage))]
[JsonSerializable(typeof(ChatAssistantProvisionalMessage))]
[JsonSerializable(typeof(ChatInterimResultMessage))]
[JsonSerializable(typeof(ChatMetricsMessage))]
[JsonSerializable(typeof(ChatResultMessage))]
[JsonSerializable(typeof(ToolDefinitionDto))]
[JsonSerializable(typeof(ToolParameterDto))]
[JsonSerializable(typeof(ToolHealthProbeDto))]
[JsonSerializable(typeof(ToolCallDto))]
[JsonSerializable(typeof(ToolOutputDto))]
[JsonSerializable(typeof(ToolRunDto))]
[JsonSerializable(typeof(TurnTimelineEventDto))]
[JsonSerializable(typeof(ModelInfoDto))]
[JsonSerializable(typeof(ReasoningEffortOptionDto))]
[JsonSerializable(typeof(TokenUsageDto))]
[JsonSerializable(typeof(ToolErrorMetricDto))]
[JsonSerializable(typeof(TurnCounterMetricDto))]
[JsonSerializable(typeof(TurnPhaseTimingDto))]
[JsonSerializable(typeof(AutonomyTelemetryDto))]
[JsonSerializable(typeof(SessionPolicyDto))]
[JsonSerializable(typeof(SessionCapabilityBackgroundSchedulerDto))]
[JsonSerializable(typeof(SessionCapabilityBackgroundSchedulerActivityDto))]
[JsonSerializable(typeof(SessionCapabilityBackgroundSchedulerSuppressionDto))]
[JsonSerializable(typeof(SessionCapabilityBackgroundSchedulerMaintenanceWindowDto))]
[JsonSerializable(typeof(SessionCapabilityBackgroundSchedulerThreadSummaryDto))]
[JsonSerializable(typeof(SessionCapabilityAutonomySummaryDto))]
[JsonSerializable(typeof(SessionCapabilitySnapshotDto))]
[JsonSerializable(typeof(SessionCapabilityParityEntryDto))]
[JsonSerializable(typeof(SessionStartupBootstrapTelemetryDto))]
[JsonSerializable(typeof(SessionStartupBootstrapPhaseTelemetryDto))]
[JsonSerializable(typeof(SessionRuntimePolicyDto))]
[JsonSerializable(typeof(SessionRoutingCatalogDiagnosticsDto))]
[JsonSerializable(typeof(SessionRoutingFamilyActionSummaryDto))]
[JsonSerializable(typeof(ToolPackAutonomySummaryDto))]
[JsonSerializable(typeof(ToolPackInfoDto))]
[JsonSerializable(typeof(ToolPackSourceKind))]
[JsonSerializable(typeof(ToolPackSourceKind[]))]
[JsonSerializable(typeof(int[]))]
public sealed partial class ChatServiceJsonContext : JsonSerializerContext;
