namespace IntelligenceX.Tests;

#if INTELLIGENCEX_REVIEWER
internal static partial class Program {
    private static void TestAnalyzeRunInternalFileSizeRuleCustomGeneratedSuffixCaseInsensitive() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-customsuffix-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:700", "generated-suffix:*.DTO.CS"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            var lines = Enumerable.Repeat("public class X { }", 705);
            File.WriteAllText(Path.Combine(temp, "Regular.cs"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "CustomGenerated.dto.cs"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "Generated.generated.cs"), string.Join('\n', lines) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var exit = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.RunAsync(new[] {
                "--workspace", temp,
                "--config", Path.Combine(temp, ".intelligencex", "reviewer.json"),
                "--out", output
            }).GetAwaiter().GetResult();

            AssertEqual(0, exit, "analyze run internal custom suffix exit");
            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run internal custom suffix findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(true, content.Contains("Regular.cs", StringComparison.Ordinal), "analyze run internal custom suffix regular");
            AssertEqual(false, content.Contains("CustomGenerated.dto.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run internal custom suffix case-insensitive");
            AssertEqual(false, content.Contains("Generated.generated.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run internal custom suffix keeps default generated suffixes");
        } finally {
            if (Directory.Exists(temp)) {
                Directory.Delete(temp, true);
            }
        }
    }

    private static void TestAnalyzeRunInternalFileSizeRuleGeneratedHeaderLineOverride() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-headerdepth-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:700", "generated-header-lines:120"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            var lines = Enumerable.Repeat("public class X { }", 705).ToArray();
            var headerLines = Enumerable.Repeat("// preamble", 100).ToArray();
            var generatedWithLongHeader = string.Join('\n', headerLines)
                + "\n// <auto-generated>\n"
                + string.Join('\n', lines)
                + "\n";
            File.WriteAllText(Path.Combine(temp, "LongHeaderGenerated.cs"), generatedWithLongHeader);
            File.WriteAllText(Path.Combine(temp, "Regular.cs"), string.Join('\n', lines) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var exit = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.RunAsync(new[] {
                "--workspace", temp,
                "--config", Path.Combine(temp, ".intelligencex", "reviewer.json"),
                "--out", output
            }).GetAwaiter().GetResult();

            AssertEqual(0, exit, "analyze run internal header depth exit");
            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run internal header depth findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(true, content.Contains("Regular.cs", StringComparison.Ordinal),
                "analyze run internal header depth regular file");
            AssertEqual(false, content.Contains("LongHeaderGenerated.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run internal header depth generated marker beyond default window");
        } finally {
            if (Directory.Exists(temp)) {
                Directory.Delete(temp, true);
            }
        }
    }

    private static void TestAnalyzeRunInternalFileSizeRuleCustomExcludedDirectory() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-excluded-dir-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));
            Directory.CreateDirectory(Path.Combine(temp, "build-cache"));
            Directory.CreateDirectory(Path.Combine(temp, "build-cache-extra"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:700", "exclude-dir:BUILD-CACHE"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            var lines = Enumerable.Repeat("public class X { }", 705);
            File.WriteAllText(Path.Combine(temp, "Regular.cs"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "build-cache", "Ignored.cs"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "build-cache-extra", "Included.cs"), string.Join('\n', lines) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var exit = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.RunAsync(new[] {
                "--workspace", temp,
                "--config", Path.Combine(temp, ".intelligencex", "reviewer.json"),
                "--out", output
            }).GetAwaiter().GetResult();

            AssertEqual(0, exit, "analyze run internal exclude-dir exit");
            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run internal exclude-dir findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(true, content.Contains("Regular.cs", StringComparison.Ordinal),
                "analyze run internal exclude-dir regular");
            AssertEqual(false, content.Contains("build-cache/Ignored.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run internal exclude-dir custom segment");
            AssertEqual(true, content.Contains("build-cache-extra/Included.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run internal exclude-dir does not match substrings");
        } finally {
            if (Directory.Exists(temp)) {
                Directory.Delete(temp, true);
            }
        }
    }

    private static void TestAnalyzeRunInternalFileSizeRuleHandlesLineEndings() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-newlines-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:700"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            File.WriteAllText(Path.Combine(temp, "LfNoTrailing.cs"), string.Join('\n', Enumerable.Repeat("public class X { }", 700)));
            File.WriteAllText(Path.Combine(temp, "CrlfNoTrailing.cs"), string.Join("\r\n", Enumerable.Repeat("public class X { }", 701)));
            File.WriteAllText(Path.Combine(temp, "LfTrailing.cs"), string.Join('\n', Enumerable.Repeat("public class X { }", 701)) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var exit = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.RunAsync(new[] {
                "--workspace", temp,
                "--config", Path.Combine(temp, ".intelligencex", "reviewer.json"),
                "--out", output
            }).GetAwaiter().GetResult();

            AssertEqual(0, exit, "analyze run internal newline exit");
            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run internal newline findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(false, content.Contains("LfNoTrailing.cs", StringComparison.Ordinal),
                "analyze run internal newline threshold respected for lf");
            AssertEqual(true, content.Contains("CrlfNoTrailing.cs", StringComparison.Ordinal),
                "analyze run internal newline crlf counted");
            AssertEqual(true, content.Contains("LfTrailing.cs", StringComparison.Ordinal),
                "analyze run internal newline lf trailing counted");
        } finally {
            if (Directory.Exists(temp)) {
                Directory.Delete(temp, true);
            }
        }
    }
}
#endif
