namespace IntelligenceX.Tests;

#if INTELLIGENCEX_REVIEWER
internal static partial class Program {
    private static void TestAnalyzeRunInternalFileSizeRuleCustomGeneratedSuffixCaseInsensitive() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-customsuffix-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:700", "generated-suffix:*.DTO.CS", "generated-suffix:.generated.cs"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            var lines = Enumerable.Repeat("public class X { }", 705);
            File.WriteAllText(Path.Combine(temp, "Regular.cs"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "CustomGenerated.dto.cs"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "Generated.generated.cs"), string.Join('\n', lines) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var exit = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.RunAsync(new[] {
                "--workspace", temp,
                "--config", Path.Combine(temp, ".intelligencex", "reviewer.json"),
                "--out", output
            }).GetAwaiter().GetResult();

            AssertEqual(0, exit, "analyze run internal custom suffix exit");
            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run internal custom suffix findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(true, content.Contains("Regular.cs", StringComparison.Ordinal), "analyze run internal custom suffix regular");
            AssertEqual(false, content.Contains("CustomGenerated.dto.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run internal custom suffix case-insensitive");
            AssertEqual(false, content.Contains("Generated.generated.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run internal custom suffix keeps default generated suffixes");
        } finally {
            DeleteDirectoryIfExistsWithRetries(temp);
        }
    }

    private static void TestAnalyzeRunInternalFileSizeRuleGeneratedHeaderLineOverride() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-headerdepth-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:700", "generated-header-lines:120", "generated-marker:<auto-generated"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            var lines = Enumerable.Repeat("public class X { }", 705).ToArray();
            var headerLines = Enumerable.Repeat("// preamble", 100).ToArray();
            var generatedWithLongHeader = string.Join('\n', headerLines)
                + "\n// <auto-generated>\n"
                + string.Join('\n', lines)
                + "\n";
            File.WriteAllText(Path.Combine(temp, "LongHeaderGenerated.cs"), generatedWithLongHeader);
            File.WriteAllText(Path.Combine(temp, "Regular.cs"), string.Join('\n', lines) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var exit = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.RunAsync(new[] {
                "--workspace", temp,
                "--config", Path.Combine(temp, ".intelligencex", "reviewer.json"),
                "--out", output
            }).GetAwaiter().GetResult();

            AssertEqual(0, exit, "analyze run internal header depth exit");
            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run internal header depth findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(true, content.Contains("Regular.cs", StringComparison.Ordinal),
                "analyze run internal header depth regular file");
            AssertEqual(false, content.Contains("LongHeaderGenerated.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run internal header depth generated marker beyond default window");
        } finally {
            DeleteDirectoryIfExistsWithRetries(temp);
        }
    }

    private static void TestAnalyzeRunInternalFileSizeRuleCustomExcludedDirectory() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-excluded-dir-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));
            Directory.CreateDirectory(Path.Combine(temp, "build-cache"));
            Directory.CreateDirectory(Path.Combine(temp, "build-cache-extra"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:700", "exclude-dir:BUILD-CACHE"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            var lines = Enumerable.Repeat("public class X { }", 705);
            File.WriteAllText(Path.Combine(temp, "Regular.cs"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "build-cache", "Ignored.cs"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "build-cache-extra", "Included.cs"), string.Join('\n', lines) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var exit = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.RunAsync(new[] {
                "--workspace", temp,
                "--config", Path.Combine(temp, ".intelligencex", "reviewer.json"),
                "--out", output
            }).GetAwaiter().GetResult();

            AssertEqual(0, exit, "analyze run internal exclude-dir exit");
            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run internal exclude-dir findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(true, content.Contains("Regular.cs", StringComparison.Ordinal),
                "analyze run internal exclude-dir regular");
            AssertEqual(false, content.Contains("build-cache/Ignored.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run internal exclude-dir custom segment");
            AssertEqual(true, content.Contains("build-cache-extra/Included.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run internal exclude-dir does not match substrings");
        } finally {
            DeleteDirectoryIfExistsWithRetries(temp);
        }
    }

    private static void TestAnalyzeRunInternalFileSizeRuleCustomExcludedPath() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-excluded-path-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));
            Directory.CreateDirectory(Path.Combine(temp, "Assets"));
            Directory.CreateDirectory(Path.Combine(temp, "Assets", "generated"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:700", "include-ext:js", "exclude-path:Assets//WIZARD.js", "exclude-path:Assets/generated"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            var lines = Enumerable.Repeat("const value = 1;", 705);
            File.WriteAllText(Path.Combine(temp, "Assets", "wizard.js"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "Assets", "wizard.js.backup.js"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "Assets", "keep.js"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "Assets", "generated", "map.js"), string.Join('\n', lines) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var result = RunAnalyzeWithConsoleOutput(temp, Path.Combine(temp, ".intelligencex", "reviewer.json"), output);

            AssertEqual(0, result.ExitCode, "analyze run internal exclude-path exit");
            AssertEqual(false, result.Output.Contains("normalized exclude-path values", StringComparison.OrdinalIgnoreCase),
                "analyze run internal exclude-path does not emit normalization noise");
            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run internal exclude-path findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(false, content.Contains("\"path\": \"Assets/wizard.js\"", StringComparison.OrdinalIgnoreCase),
                "analyze run internal exclude-path custom file");
            AssertEqual(true, content.Contains("\"path\": \"Assets/wizard.js.backup.js\"", StringComparison.OrdinalIgnoreCase),
                "analyze run internal exclude-path does not exclude near-prefix file");
            AssertEqual(true, content.Contains("\"path\": \"Assets/keep.js\"", StringComparison.OrdinalIgnoreCase),
                "analyze run internal exclude-path still reports other files");
            AssertEqual(true, content.Contains("\"path\": \"Assets/generated/map.js\"", StringComparison.OrdinalIgnoreCase),
                "analyze run internal exclude-path does not exclude subpath");
        } finally {
            DeleteDirectoryIfExistsWithRetries(temp);
        }
    }

    private static void TestAnalyzeRunInternalFileSizeRuleExcludePathNormalizesRepeatedSeparators() {
        var matched = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.IsPathExcludedByConfiguredPathsForTests(
            "Assets//wizard.js",
            "Assets/wizard.js");
        AssertEqual(true, matched, "analyze run internal exclude-path normalizes repeated separators");

        var stillMatched = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.IsPathExcludedByConfiguredPathsForTests(
            "Assets\\\\wizard.js",
            "Assets/wizard.js");
        AssertEqual(true, stillMatched, "analyze run internal exclude-path normalizes slash variants");

        var notMatched = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.IsPathExcludedByConfiguredPathsForTests(
            "Assets/wizard.backup.js",
            "Assets/wizard.js");
        AssertEqual(false, notMatched, "analyze run internal exclude-path remains exact after normalization");
    }

    private static void TestAnalyzeRunInternalFileSizeRuleHandlesLineEndings() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-newlines-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:700"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            File.WriteAllText(Path.Combine(temp, "LfNoTrailing.cs"), string.Join('\n', Enumerable.Repeat("public class X { }", 700)));
            File.WriteAllText(Path.Combine(temp, "CrlfNoTrailing.cs"), string.Join("\r\n", Enumerable.Repeat("public class X { }", 701)));
            File.WriteAllText(Path.Combine(temp, "LfTrailing.cs"), string.Join('\n', Enumerable.Repeat("public class X { }", 701)) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var exit = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.RunAsync(new[] {
                "--workspace", temp,
                "--config", Path.Combine(temp, ".intelligencex", "reviewer.json"),
                "--out", output
            }).GetAwaiter().GetResult();

            AssertEqual(0, exit, "analyze run internal newline exit");
            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run internal newline findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(false, content.Contains("LfNoTrailing.cs", StringComparison.Ordinal),
                "analyze run internal newline threshold respected for lf");
            AssertEqual(true, content.Contains("CrlfNoTrailing.cs", StringComparison.Ordinal),
                "analyze run internal newline crlf counted");
            AssertEqual(true, content.Contains("LfTrailing.cs", StringComparison.Ordinal),
                "analyze run internal newline lf trailing counted");
        } finally {
            DeleteDirectoryIfExistsWithRetries(temp);
        }
    }

    private static void TestAnalyzeRunInternalFileSizeRuleWarnsOnMalformedTags() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-malformed-tags-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:not-a-number", "generated-header-lines:-5", "generated-suffix:"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            var lines = Enumerable.Repeat("public class X { }", 705);
            File.WriteAllText(Path.Combine(temp, "Regular.cs"), string.Join('\n', lines) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var result = RunAnalyzeWithConsoleOutput(temp, Path.Combine(temp, ".intelligencex", "reviewer.json"), output);

            AssertEqual(0, result.ExitCode, "analyze run malformed tags exit");
            AssertEqual(true, result.Output.Contains("malformed tag 'max-lines:not-a-number'", StringComparison.OrdinalIgnoreCase),
                "analyze run malformed tags max-lines warning");
            AssertEqual(true, result.Output.Contains("malformed tag 'generated-header-lines:-5'", StringComparison.OrdinalIgnoreCase),
                "analyze run malformed tags header-lines warning");
            AssertEqual(true, result.Output.Contains("has malformed tags", StringComparison.OrdinalIgnoreCase) &&
                result.Output.Contains("'generated-suffix:'", StringComparison.OrdinalIgnoreCase),
                "analyze run malformed tags suffix warning");

            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run malformed tags findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(true, content.Contains("Regular.cs", StringComparison.Ordinal), "analyze run malformed tags fallback still reports file");
        } finally {
            DeleteDirectoryIfExistsWithRetries(temp);
        }
    }

    private static void TestAnalyzeRunInternalFileSizeRuleWarnsOnUnknownTagPrefixes() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-unknown-tags-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:700", "max-linez:650", "generated-sufix:.generated.cs"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            var lines = Enumerable.Repeat("public class X { }", 705);
            File.WriteAllText(Path.Combine(temp, "Regular.cs"), string.Join('\n', lines) + "\n");
            File.WriteAllText(Path.Combine(temp, "Generated.generated.cs"), string.Join('\n', lines) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var result = RunAnalyzeWithConsoleOutput(temp, Path.Combine(temp, ".intelligencex", "reviewer.json"), output);

            AssertEqual(0, result.ExitCode, "analyze run unknown tags exit");
            AssertEqual(true, result.Output.Contains("unknown maintainability tags", StringComparison.OrdinalIgnoreCase) &&
                result.Output.Contains("'max-linez:650'", StringComparison.OrdinalIgnoreCase),
                "analyze run unknown tags max-lines typo warning");
            AssertEqual(true, result.Output.Contains("'generated-sufix:.generated.cs'", StringComparison.OrdinalIgnoreCase),
                "analyze run unknown tags generated suffix typo warning");

            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run unknown tags findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(true, content.Contains("Generated.generated.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run unknown tags does not silently apply typoed suffix");
        } finally {
            DeleteDirectoryIfExistsWithRetries(temp);
        }
    }

    private static void TestAnalyzeRunInternalFileSizeRuleGeneratedHeaderScanCanBeDisabled() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-header-disabled-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 700 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:700", "generated-header-lines:0", "generated-marker:<auto-generated"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            var lines = Enumerable.Repeat("public class X { }", 705);
            File.WriteAllText(Path.Combine(temp, "HeaderGenerated.cs"),
                "// <AUTO-GENERATED>\n" + string.Join('\n', lines) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var exit = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.RunAsync(new[] {
                "--workspace", temp,
                "--config", Path.Combine(temp, ".intelligencex", "reviewer.json"),
                "--out", output
            }).GetAwaiter().GetResult();

            AssertEqual(0, exit, "analyze run header disabled exit");
            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run header disabled findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(true, content.Contains("HeaderGenerated.cs", StringComparison.OrdinalIgnoreCase),
                "analyze run header disabled does not exclude file by marker");
        } finally {
            DeleteDirectoryIfExistsWithRetries(temp);
        }
    }

    private static void TestAnalyzeRunInternalFileSizeRuleGeneratedHeaderMarkerSupportsHashComments() {
        var temp = Path.Combine(Path.GetTempPath(), "ix-analyze-size-header-hash-comment-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try {
            Directory.CreateDirectory(Path.Combine(temp, ".intelligencex"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal"));
            Directory.CreateDirectory(Path.Combine(temp, "Analysis", "Packs"));

            File.WriteAllText(Path.Combine(temp, ".intelligencex", "reviewer.json"), """
{
  "analysis": {
    "enabled": true,
    "packs": ["intelligencex-maintainability-default"]
  }
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Catalog", "rules", "internal", "IXLOC001.json"), """
{
  "id": "IXLOC001",
  "language": "internal",
  "tool": "IntelligenceX.Maintainability",
  "toolRuleId": "IXLOC001",
  "title": "Source files should stay below 5 lines",
  "description": "Flags oversized source files.",
  "category": "Maintainability",
  "defaultSeverity": "warning",
  "tags": ["max-lines:5", "include-ext:py", "generated-marker:<auto-generated"]
}
""");

            File.WriteAllText(Path.Combine(temp, "Analysis", "Packs", "intelligencex-maintainability-default.json"), """
{
  "id": "intelligencex-maintainability-default",
  "label": "IntelligenceX Maintainability",
  "rules": ["IXLOC001"]
}
""");

            var lines = Enumerable.Repeat("value += 1", 20);
            File.WriteAllText(Path.Combine(temp, "Generated.py"),
                "# <auto-generated>\n" +
                "value = 0\n" +
                string.Join('\n', lines) + "\n");

            var output = Path.Combine(temp, "artifacts");
            var exit = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.RunAsync(new[] {
                "--workspace", temp,
                "--config", Path.Combine(temp, ".intelligencex", "reviewer.json"),
                "--out", output
            }).GetAwaiter().GetResult();

            AssertEqual(0, exit, "analyze run hash header marker exit");
            var findingsPath = Path.Combine(output, "intelligencex.findings.json");
            AssertEqual(true, File.Exists(findingsPath), "analyze run hash header marker findings exists");
            var content = File.ReadAllText(findingsPath);
            AssertEqual(false, content.Contains("Generated.py", StringComparison.OrdinalIgnoreCase),
                "analyze run hash header marker excludes generated python file");
        } finally {
            DeleteDirectoryIfExistsWithRetries(temp);
        }
    }

    private static (int ExitCode, string Output) RunAnalyzeWithConsoleOutput(string workspace, string configPath, string outputPath) {
        var originalOut = Console.Out;
        using var writer = new StringWriter();
        Console.SetOut(writer);
        try {
            var exitCode = IntelligenceX.Cli.Analysis.AnalyzeRunCommand.RunAsync(new[] {
                "--workspace", workspace,
                "--config", configPath,
                "--out", outputPath
            }).GetAwaiter().GetResult();
            return (exitCode, writer.ToString());
        } finally {
            Console.SetOut(originalOut);
        }
    }
}
#endif
