name: Deploy Website

on:
  push:
    branches: [master]
    paths:
      - 'Website/**'
      - 'Docs/**'
      - '.github/workflows/deploy-website.yml'
  workflow_dispatch:

permissions:
  actions: write
  contents: read
  pages: write
  id-token: write

jobs:
  website-deploy:
    uses: EvotecIT/PSPublishModule/.github/workflows/powerforge-website-deploy.yml@7a64f111a4d7bf7f52a34a4392ad3ced67b6049c
    with:
      website_root: Website
      pipeline_config: Website/pipeline.json
      site_output_path: Website/_site
      post_deploy_pipeline_config: Website/pipeline.cloudflare.json
      engine_mode: binary
      runner_labels_json: ${{ (github.event.repository.private && vars.IX_FORCE_GITHUB_HOSTED != 'true') && '["self-hosted","linux"]' || '["ubuntu-latest"]' }}
      powerforge_repository: EvotecIT/PSPublishModule
      powerforge_ref: 7a64f111a4d7bf7f52a34a4392ad3ced67b6049c
      powerforge_tool_lock_path: Website/.powerforge/tool-lock.json
    secrets:
      indexnow_key: ${{ secrets.INDEXNOW_KEY }}
      cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      cloudflare_zone_id: ${{ secrets.CLOUDFLARE_ZONE_ID_IX }}
