name: Website Build (PR)

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  website-build:
    uses: EvotecIT/PSPublishModule/.github/workflows/powerforge-website-ci.yml@b1d807d0ba277b92f6287e3c5d828ec833c45081
    with:
      website_root: Website
      pipeline_config: Website/pipeline.json
      engine_mode: source
      runner_labels_json: ${{ (github.event.repository.private && vars.IX_FORCE_GITHUB_HOSTED != 'true') && '["self-hosted","linux"]' || '["ubuntu-latest"]' }}
      powerforge_repository: EvotecIT/PSPublishModule
      powerforge_ref: b1d807d0ba277b92f6287e3c5d828ec833c45081
